net/samba410: disable DEBUG on powerpc64
-O0 breaks assumption that the compiler is optimizing functions, which leads to unresolved symbols:
ld: error: /wrkdirs/usr/ports/net/samba410/work/samba-4.10.13/bin/default/source3/libsmbd-base-samba4.so: undefined reference to __unsafe_string_function_usage_here_NTSTATUS__

DEBUG option probably shouldn't be on by default anyway, but I assume there must be some reason for it.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@525653 35697150-7ecd-e111-bb59-0022644237b5