net/widentd: disable -Werror
On gcc, this warning is given:

widentd.c: In function 'main':
widentd.c:194:3: error: 'memset' used with constant zero length parameter;
  this could be due to transposed parameters
  [-Werror=memset-transposed-args]
   memset(buff, sizeof(buff), 0);
   ^

Removing -Werror is blanket-approved.  This is another port that uses
<bsd.prog.mk> instead of providing an independent makefile, so the
-Werror is coming from the system build framework.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@382958 35697150-7ecd-e111-bb59-0022644237b5