Add missing dependencies to pass `make stage-qa'.
Error: /usr/local/bin/cmake-gui is linked to /usr/local/lib/libexecinfo.so.1 from devel/libexecinfo but it is not declared as a dependency
Warning: you need USES+=execinfo
Error: /usr/local/bin/cmake-gui is linked to /usr/local/lib/libjsoncpp.so.1 from devel/jsoncpp but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libjsoncpp.so:devel/jsoncpp


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@418346 35697150-7ecd-e111-bb59-0022644237b5