- Add missing dependency on qt corelib - Fix dependency on python: require 2.7, fails with python3:
bindings/python/qrosspython/cxx/IndirectPythonInterface.cxx:469:12: error: unknown type name 'DL_IMPORT'
extern "C" DL_IMPORT(PyTypeObject) PyRange_Type;
           ^
bindings/python/qrosspython/cxx/IndirectPythonInterface.cxx:469:35: error: expected ';' after top level declarator
extern "C" DL_IMPORT(PyTypeObject) PyRange_Type;
                                  ^
                                  ;
bindings/python/qrosspython/cxx/IndirectPythonInterface.cxx:470:34: error: expected function body after function declarator
extern "C" DL_IMPORT(PyObject *) PyRange_New(long, long, long, int);
                                 ^
bindings/python/qrosspython/cxx/IndirectPythonInterface.cxx:497:44: error: no member named 'PyExc_MemoryErrorInst' in the global namespace; did you mean '_Exc_MemoryErrorInst'?
PyObject * _Exc_MemoryErrorInst() { return ::PyExc_MemoryErrorInst; }
                                           ^~~~~~~~~~~~~~~~~~~~~~~
                                           _Exc_MemoryErrorInst
...

- Fix dependency on py-sip (use flavors to depend on correct version)
- Switch to opt_CMAKE_BOOL

Approved by:	portmgr blanket


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@461081 35697150-7ecd-e111-bb59-0022644237b5