net-mgmt/nfdump: fix build on GCC architectures and check-plist on others
Use C11 compiler:
In file included from nfcapd.c:69:
nfx.h:946: error: redefinition of typedef 'extension_map_t'
nfdump.h:64: error: previous declaration of 'extension_map_t' was here
In file included from nfcapd.c:70:
exporter.h:78: error: redefinition of typedef 'exporter_info_record_t'
nfdump.h:63: error: previous declaration of 'exporter_info_record_t' was here

Remove unconditional installation of nfpcapd, it breaks check-plist and there's an option for installing it.

Bump PORTREVISION for package change.

MFH:		2020Q3 (fix build blanket, packaging fix)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@546277 35697150-7ecd-e111-bb59-0022644237b5