games/marsnomercy: Fix build with Clang 6
src/mars.cpp:423:29: error: non-constant-expression cannot be narrowed from type 'int' to 'Sint16' (aka 'short') in initializer list [-Wc++11-narrowing]
        SDL_Rect mm_limit_1024 = { (mm.GetW() - (mm_border_1024->GetW() - 2)) / 2, 0,
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475044_s336572/logs/marsnomercy-0.2.1_12.log

- Add missing libpng dependency


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@475506 35697150-7ecd-e111-bb59-0022644237b5