Use iconv port, for wchar_t.
When running the plexhometheater player, the following line is repeatedly
printed into the log output.

ERROR: convert_checked iconv_open() failed from UTF-8 to WCHAR_T, errno=22(Invalid argument)

This is because the plexhometheater port currently uses the iconv in base,
which does not provide the wchar_t functionality.

PR:		194533
Submitted by:	Ben Woods (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@371361 35697150-7ecd-e111-bb59-0022644237b5