security/masscan: fix build on powerpc(64) head
Use GCC instead of clang:
/usr/lib/clang/10.0.0/include/mmintrin.h:525:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@533887 35697150-7ecd-e111-bb59-0022644237b5