graphics/hdr_tools: fix build with GCC-based architectures
Replace USES=compiler:features with USES=compiler:c++11-lang. c++11-lang includes features anyway.

This fixes linking errors when base GCC is used:
/usr/local/lib/libIlmImf.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
Approved by:	mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@500802 35697150-7ecd-e111-bb59-0022644237b5