During the exp-run in bug 208158, it was found that dns/powerdns gives errors with libc++ 3.8.0:
dnspacket.cc:645:6: error: call to 'abs' is ambiguous
  if(abs(trc->d_time - now) > trc->d_fudge) {
     ^~~

This is because abs() is being called with unsigned arguments.  Import
upstream commit f2d05dd to fix it.

Approved by:	tremere@cainites.net
PR:		208725
MFH:		2016Q2


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@414065 35697150-7ecd-e111-bb59-0022644237b5