math/fityk: unbreak build on 8.x/9.x (gcc 4.8)
Add -std=c++11 to fix

  /usr/local/include/wx-3.0/wx/strvararg.h:25:27: error: type_traits: No such file or directory

which itself exposes

  guess.cpp:20:7: error: unknown type name 'array'
  const array<string, 3> Guess::linear_traits =
        ^
  sidebar.cpp:900:52: error: invalid suffix on literal; C++11 requires a space between
        literal and identifier [-Wreserved-user-defined-literal]
                     + s2wx(format1<realt, 30>("%.10"REALT_LENGTH_MOD"g", a)));
                                                     ^
Reported by:	pkg-fallout
Approved by:	portmgr blanket
MFH:		2015Q2 (only USES due to lack of r383466)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@385070 35697150-7ecd-e111-bb59-0022644237b5