games/libretro-bluemsx: fix build on powerpc64le
Src/SoundChips/OpenMsxYM2413.cpp:331:10: error: constant expression evaluates to -3 which cannot be narrowed to type 'char' [-Wc++11-narrowing]
        7, 3, 0,-3,-7,-3, 0, 3,

Since it should also fix build on other architectures with unsigned char, unbreak on aarch64 and riscv64 (untested).


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@565317 35697150-7ecd-e111-bb59-0022644237b5