www/py-apachelog: convert to USES=python
- convert to USES=python
- limit to python2:
  """
  File "/usr/local/lib/python3.4/site-packages/apachelog.py", line 170
    except Exception, e:
                    ^
  SyntaxError: invalid syntax
  """

Approved by:	portmgr (blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@371109 35697150-7ecd-e111-bb59-0022644237b5