After upgrading to 11.2-RELEASE devel/avarice fails to compile with:
    jtagrw.cc:134:13: error: cannot initialize return object of type 'uchar *' (aka 'unsigned char *') with an rvalue of type 'bool'

		return false;
		       ^~~~~

examination of the code shows another case with a similar
check that returns NULL.

I also filed an upstream bug report:

    https://sourceforge.net/p/avarice/bugs/24/

PR:		229376
Reviewed by:	ler (mentor)
Approved by:	joerg (maintainer), ler (mentor)
Differential Revision:	https://reviews.freebsd.org/D16184


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@474207 35697150-7ecd-e111-bb59-0022644237b5