Avoid building with GCC 10 due to:
  types.h:95:37: error: 'asm' operand has impossible constraints

PR:		246700
Approved by:	maintainer


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@555597 35697150-7ecd-e111-bb59-0022644237b5