net/libnfs: fix build error regarding "redefinition of typedef"
libnfs was redefining u_int, causing programs using libnfs to get
"error: redefinition of typedef 'u_int' is a C11 feature" errors.

Upstream PR: https://github.com/sahlberg/libnfs/pull/326

PR:		248296
Approved by:	Shannon Noe <snoe925@gmail.com> (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@544646 35697150-7ecd-e111-bb59-0022644237b5