sysutils/py-tmuxp: update to 0.9.0
This release fixing compatibility with tmux 2.0.

While here, limit python version to 2.x:

"""
===>  Configuring for py34-tmuxp-0.9.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 25, in <module>
    readme = open('README.rst').read()
  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 635: ordinal not in range(128)
"""

PR:		201431
Submitted by:	Tony Narlock <tony@git-pull.com> (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@392042 35697150-7ecd-e111-bb59-0022644237b5