- Add missing LIB_DEPENDS via WANT_PGSQL=lib - Enable RASTER by default - Fix PLIST - Bump PORTREVISION for package change
====> Running Q/A tests (stage-qa)
Error: /usr/local/bin/pgsql2shp is linked to /usr/local/lib/libpq.so.5 from databases/postgresql96-client but it is not declared as a dependency
Warning: you need USES+=pgsql


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@428183 35697150-7ecd-e111-bb59-0022644237b5