multimedia/py-moviepy: Unbreak: it couldn't find the ffmpeg executable
This line:
from moviepy.editor import *

resulted in failure:
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 77, in download
    raise RuntimeError("FFMPEG exe isn't available for platform %s" % plat)
RuntimeError: FFMPEG exe isn't available for platform freebsd64

This is because it uses py-imageio to download the ffmpeg binary which doesn't exist for FreeBSD.
Besides, py-imageio is downloading files without checking cryptographic fingerprints wihich is insecure: https://github.com/imageio/imageio/issues/416

Solution:
Make py-moviepy to always use the pre-installed ffmpeg package.

Approved by:	portmgr (unbreak)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@487621 35697150-7ecd-e111-bb59-0022644237b5