Mark broken: Does not compile
On 8 and 9:
Compiling libmapi/IMessage.c with -fPIC
libmapi/IMessage.c: In function 'ModifyRecipients':
libmapi/IMessage.c:764: error: 'struct ndr_push' has no member named 'iconv_convenience'
libmapi/IMessage.c:764: warning: implicit declaration of function 'smb_iconv_convenience_init'
gmake: *** [libmapi/IMessage.po] Error 1
*** Error code 1

On 10 and head:
libmapi/IMessage.c:764:8: error: no member named 'iconv_convenience' in 'struct ndr_push'
                ndr->iconv_convenience = smb_iconv_convenience_init(mem_ctx, "CP850", "UTF8", true);
                ~~~  ^
libmapi/IMessage.c:764:28: warning: implicit declaration of function 'smb_iconv_convenience_init' is invalid in C99 [-Wimplicit-function-declaration]
                ndr->iconv_convenience = smb_iconv_convenience_init(mem_ctx, "CP850", "UTF8", true);
                                         ^
1 warning and 1 error generated.
gmake[1]: *** [libmapi/IMessage.po] Error 1
gmake[1]: Leaving directory `/wrkdirs/usr/ports/mail/libmapi/work/openchange-0.9-COCHRANE'
*** Error code 1

Reported by:	pkg-fallout since august 2013
With hat:	portmgr


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@342086 35697150-7ecd-e111-bb59-0022644237b5