gecko: unbreak RUST=on with cargo >= 0.18
error[E0463]: can't find crate for `cheddar`
 --> media/libstagefright/binding/mp4parse_capi/build.rs:1:1
  |
1 | extern crate cheddar;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

fatal runtime error: failed to initiate panic, error 5
error: Could not compile `mp4parse_capi`.

Caused by:
  process didn't exit successfully: `/usr/local/bin/rustc --crate-name build_script_build media/libstagefright/binding/mp4parse_capi/build.rs --crate-type bin --emit=dep-info,link -C opt-level=2 -C debuginfo=2 -C metadata=13cd8b0152b68b4e -C extra-filename=-13cd8b0152b68b4e--out-dir obj-x86_64-unknown-freebsd12.0/toolkit/library/rust/./release/build/mp4parse_capi-13cd8b0152b68b4e -L dependency=obj-x86_64-unknown-freebsd12.0/toolkit/library/rust/./release/deps` (exit code: 1)
Build failed, waiting for other jobs to finish...
error: build failed


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@439925 35697150-7ecd-e111-bb59-0022644237b5