net-mgmt/bandwhich: fix build after r551268
Apparently the build fails (I can't replicate the issue on my builders)

===>  Configuring for bandwhich-0.19.0
    Updating git repository `https://github.com/tailhook/resolv-conf`
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Name does not resolve; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Name does not resolve; class=Net (12)
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `resolv-conf`

PR:		249571
Reported by:	olgeni
Approved by:	portmgr (implicit, build fix)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@551477 35697150-7ecd-e111-bb59-0022644237b5