Update Phonon to 4.9.0.
Release notes:
- https://community.kde.org/Phonon/Releases/Core/4.9.0
- https://community.kde.org/Phonon/Releases/GStreamer/4.9.0
- https://community.kde.org/Phonon/Releases/VLC/0.9.0

This release fixes the build with the upcoming Qt 5.6, which was failing like
this:

    /usr/bin/c++   -O2 -pipe -fstack-protector -fno-strict-aliasing -Wnon-virtual-dtor -Wno-long-long -Wundef -Wcast-align -Wchar-subscripts -Wall -W -Wpointer-arith -Wformat-security -Woverloaded-virtual -fno-common -fvisibility=hidden -Werror=return-type -fvisibility-inlines-hidden -Wno-return-type-c-linkage     CMakeFiles/cmTC_08ed6.dir/check_qt_visibility.cpp.o  -o cmTC_08ed6
    CMakeFiles/cmTC_08ed6.dir/check_qt_visibility.cpp.o:(.qtversion[qt_version_tag]+0x0): undefined reference to `qt_version_tag'

Most of the work was done by tcberner@.

PR:		211916


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@421340 35697150-7ecd-e111-bb59-0022644237b5