Mark BROKEN everywhere: fails to link
cd subversion/svn && /bin/sh "/wrkdirs/usr/ports/devel/subversion-static/work/subversion-1.9.7/libtool" --tag=CC --silent --mode=link cc -all-static -Werror=unknown-warning-option -O2 -pipe  -fpic -DPIC -fstack-protector -fno-strict-aliasing   -O2 -pipe  -fpic -DPIC -fstack-protector -fno-strict-aliasing  -fstack-protector  -L/usr/local/lib -L/usr/local/lib/db5 -L/usr/local/lib           -L/usr/local/lib  -rpath /usr/local/lib  -o svn  add-cmd.lo auth-cmd.lo blame-cmd.lo cat-cmd.lo changelist-cmd.lo checkout-cmd.lo cl-conflicts.lo cleanup-cmd.lo commit-cmd.lo conflict-callbacks.lo copy-cmd.lo delete-cmd.lo deprecated.lo diff-cmd.lo export-cmd.lo file-merge.lo help-cmd.lo import-cmd.lo info-cmd.lo list-cmd.lo lock-cmd.lo log-cmd.lo merge-cmd.lo mergeinfo-cmd.lo mkdir-cmd.lo move-cmd.lo notify.lo patch-cmd.lo propdel-cmd.lo propedit-cmd.lo propget-cmd.lo proplist-cmd.lo props.lo propset-cmd.lo relocate-cmd.lo resolve-cmd.lo resolved-cmd.lo revert-cmd.lo similarity.lo status-cmd.lo status.lo svn.lo switch-cmd.lo unlock-cmd.lo update-cmd.lo upgrade-cmd.lo util.lo ../../subversion/libsvn_client/libsvn_client-1.la ../../subversion/libsvn_wc/libsvn_wc-1.la ../../subversion/libsvn_ra/libsvn_ra-1.la ../../subversion/libsvn_delta/libsvn_delta-1.la ../../subversion/libsvn_diff/libsvn_diff-1.la ../../subversion/libsvn_subr/libsvn_subr-1.la -L/usr/local/lib -laprutil-1 -ldb-5.3 -lgdbm -lexpat -L/usr/local/lib -lapr-1 -lcrypt -lpthread
/usr/local/lib/libsqlite3.a(sqlite3.o): In function `fts5Bm25Function':
(.text+0xf936a): undefined reference to `log'

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@456681 35697150-7ecd-e111-bb59-0022644237b5