science/qiskit-aer: Broken on i386 due to undefined reference to `__atomic_load'
Reported by:	fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@528495 35697150-7ecd-e111-bb59-0022644237b5