- Update *_DEPENDS - Bump PORTREVISION for dependency change - While I'm here, fix check-plist error
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: BBBike/tmp/.keep_me
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/german/BBBike
====>> Error: check-plist failures detected


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@376093 35697150-7ecd-e111-bb59-0022644237b5