- Add back part of LDFLAGS removed in r387982, it's needed to link at least on FreeBSD 9.3: fluid_sys.c:(.text+0xced): undefined reference to `pthread_setschedparam'
- While here, fix a typo in an option helper


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@388047 35697150-7ecd-e111-bb59-0022644237b5