net/mpich: fix build on powerpc64
Neither __BYTE_ORDER nor __BIG_ENDIAN are defined:
In file included from src/mpi/datatype/typerep/dataloop/looputil.c:10:
./src/mpi/datatype/typerep/dataloop/looputil.h:57:2: error: This code assumes that __BYTE_ORDER and __BIG_ENDIAN are defined
#error This code assumes that __BYTE_ORDER and __BIG_ENDIAN are defined


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@561371 35697150-7ecd-e111-bb59-0022644237b5