sysutils/shim: introduce new ARCH support (i386)
    Makefile
        bump PORTREVISION;
        USE_CSTD: gnu89 became gnu99 [0];

    files/
        *: if ARCH=i386, replaces ARCH with ia32;
        elf_ia32_efi.lds: sync OUTPUT_FORMAT [1];
        MokManager.c: used UINT32 for MokNum.

Reported by:	pkg-fallout
Approved by:	araujo (mentor)
Differential Revision:	https://reviews.freebsd.org/D18572

[0] shim.c:2176:3: error: this decimal constant is unsigned only in ISO C90
[1] patch-elf_x86_64_efi.lds always appended -freebsd as OUTPUT_FORMAT


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@487805 35697150-7ecd-e111-bb59-0022644237b5