lang/luajit-openresty: fix build on powerpc64 elfv2
lua_assert is undefined, which makes build fail with:
/usr/local/bin/ld: libluajit.a(lj_ccallback.o): in function `lj_ccallback_new':
lj_ccallback.c:(.text+0xbc8): undefined reference to `lua_assert'

lua_assert is defined in lualib.h.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@553603 35697150-7ecd-e111-bb59-0022644237b5