sysutils/twmn: Update to g20190917, unbreak with clang 10
In file included from /usr/local/include/qt5/QtCore/qstring.h:49:
/usr/local/include/qt5/QtCore/qbytearray.h:545:22: error: definition of implicit copy constructor for 'QByteRef' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
    inline QByteRef &operator=(const QByteRef &c)
                     ^
/usr/local/include/qt5/QtCore/qbytearray.h:563:28: note: in implicit copy constructor for 'QByteRef' first required here
{ Q_ASSERT(i >= 0); return QByteRef(*this, i); }
                           ^

PR:		244251


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@528654 35697150-7ecd-e111-bb59-0022644237b5