security/softether5: fix build on GCC architectures
Require C11 compiler:
/wrkdirs/usr/ports/security/softether5/work/SoftEtherVPN-5.01.9671/src/./Mayaqua/Str.h:204: error: redefinition of typedef 'UINT'

Reviewed by:	mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@507379 35697150-7ecd-e111-bb59-0022644237b5