*/lumina-*: Unbreak I18N options
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/lumina-desktop/i18n/l-screenshot_af.qm
Error: Missing: share/lumina-desktop/i18n/l-screenshot_ar.qm
Error: Missing: share/lumina-desktop/i18n/l-screenshot_az.qm
...

- Add missing USE_QT5=printsupport to lumina-textedit

PR:		224860
Submitted by:	tobik
Approved by:	jt@ixsystems.com (maintainer), araujo


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@470276 35697150-7ecd-e111-bb59-0022644237b5