Mark as BROKEN on powerpc64 due to variants of:
  /usr/local/include/dmlc/./serializer.h:63:11: error: no member named 'Write' in 'dmlc::serializer::UndefinedSerializerFor<xgboost::DataType>'

Approved by:	portmgr (tier-2 blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@535700 35697150-7ecd-e111-bb59-0022644237b5