Fix a possible crash due to an undefined reference to gethostbyname_r().
PR:		28685
Submitted by:	Ken Lui <klui@cup.hp.com>


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@45203 aed309b6-a8cd-e111-996c-001c23d10e55