graphics/colmap: unblock on amd64 due to intermittent errors
FreeBSD 9.3 amd64:
  51: Test command: src/util/threading_test
  51: Test timeout computed to be: 9.99988e+06
  51: Running 23 test cases...
  51: src/util/threading_test.cc(309): error: in "TestDefaultCallback": check called_back1 has failed
  51:
  51: *** 1 failure is detected in the test module "util/threading"

FreeBSD 11.0 amd64:
  51: Test command: src/util/threading_test
  51: Test timeout computed to be: 9.99988e+06
  51: Running 23 test cases...
  51: src/util/threading_test.cc(183): error: in "TestThreadPauseStop": check thread.IsRunning() has failed
  51: src/util/threading_test.cc(184): error: in "TestThreadPauseStop": check !thread.IsFinished() has failed
  51:
  51: *** 2 failures are detected in the test module "util/threading"

Reported by:	pkg-fallout (r428457 and r428600 builds were green)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@428766 35697150-7ecd-e111-bb59-0022644237b5