security/wolfssl: Fix QA issues
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%DOCSDIR%%/README.txt
Error: Missing: %%DOCSDIR%%/example/client.c
Error: Missing: %%DOCSDIR%%/example/echoclient.c
Error: Missing: %%DOCSDIR%%/example/echoserver.c
Error: Missing: %%DOCSDIR%%/example/sctp-client-dtls.c
Error: Missing: %%DOCSDIR%%/example/sctp-client.c
Error: Missing: %%DOCSDIR%%/example/sctp-server-dtls.c
Error: Missing: %%DOCSDIR%%/example/sctp-server.c
Error: Missing: %%DOCSDIR%%/example/server.c
Error: Missing: %%DOCSDIR%%/example/tls_bench.c
Error: Missing: %%DOCSDIR%%/taoCert.txt
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/security/wolfssl
=>> Error: check-plist failures detected
=>> Checking for staging violations... done
=======================<phase: package        >============================
===>  Building package for wolfssl-4.6.0_1
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/README.txt, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/tls_bench.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/sctp-server.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/echoserver.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/sctp-client-dtls.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/sctp-server-dtls.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/echoclient.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/client.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/server.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/example/sctp-client.c, fatal (developer mode)
pkg-static: duplicate file listing: /usr/local/share/doc/wolfssl/taoCert.txt, fatal (developer mode)

http://package21.nyi.freebsd.org/data/114amd64-default-qat/566258/logs/errors/wolfssl-4.6.0_1.log


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@566484 35697150-7ecd-e111-bb59-0022644237b5