www/firefox: unbreak build with DEBUG=on after r425099
Traceback (most recent call last):
  File "configure.py", line 94, in <module>
    sys.exit(main(sys.argv))
  File "configure.py", line 22, in main
    sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
  File "python/mozbuild/mozbuild/configure/__init__.py", line 241, in run
    self._value_for(option)
  File "python/mozbuild/mozbuild/configure/__init__.py", line 305, in _value_for
    return self._value_for_option(obj)
  File "python/mozbuild/mozbuild/util.py", line 924, in method_call
    cache[args] = self.func(instance, *args)
  File "python/mozbuild/mozbuild/configure/__init__.py", line 370, in _value_for_option
    % (e.arg, reason, e.old_arg, e.old_origin))
mozbuild.configure.options.InvalidOptionError: '--enable-debug-symbols' implied by '--enable-debug' conflicts with '--disable-debug-symbols' from the mozconfig
*** Fix above errors and then restart with\
               "gmake -f client.mk build"

MFH:		2016Q4 (blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@425281 35697150-7ecd-e111-bb59-0022644237b5