Mark broken: Does not build
On 8 and 9:
Services/RadioService/RadioService.cpp: In member function 'void RadioService::onPhononStateChanged(Phonon::State, Phonon::State)':
Services/RadioService/RadioService.cpp:312: error: ambiguous overload for 'operator<<' in 'StampedDebug(QtDebugMsg, ((const QByteArray&)(& QByteArray(((const char*)"Services/RadioService/RadioService.cpp")))), 312u, QByteArray(((const char*)(& __PRETTY_FUNCTION__)))) << oldstate'

On 10 and head:
cd app/client/ && /usr/bin/make -f Makefile all
make[2]: don't know how to make ../../_bin/Last.fm\. Stop

make[2]: stopped in /wrkdirs/usr/ports/audio/lastfm-desktop/work/lastfm-desktop-2.1.30/app/client
*** Error code 2

Reported by:	pkg-fallout since november 2013


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@345580 35697150-7ecd-e111-bb59-0022644237b5