cad/graywolf: Fix build on 13
sys/dir.h is replaced with dirent.h

fatal error: sys/dir.h: No such file or directory
  136 | #include <sys/dir.h>
      |          ^~~~~~~~~~~


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@529773 35697150-7ecd-e111-bb59-0022644237b5