Mark as broken:
getline.h:37: error: declaration of C function 'int getline(char**, size_t*,
FILE*)' conflicts with
/usr/include/stdio.h:371: error: previous declaration 'ssize_t getline(char**,
size_t*, FILE*)' here


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@311705 aed309b6-a8cd-e111-996c-001c23d10e55