databases/freetds-devel: fix build with GCC-based architectures
Base GCC doesn't have __builtin_bswap16:
./.libs/libtdssrv.a(lt1-login.o):(.text+0x166c): undefined reference to `__builtin_bswap16'

Approved by:	mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@507529 35697150-7ecd-e111-bb59-0022644237b5