Fix builds of net/samba46 and net/samba47 when using lld 7.0.0.
With lld 7.0.0, the following error is emitted:

  ld: error: duplicate symbol 'pdb_search_init' in version script

This is because the symbol version scripts generated by wscript_build
contain both "pdb_search_init" in the global section, and "pdb_*_init"
in the local section.  Fix it by removing "pdb_*_init" from the local
section.

For net/samba48, this already got fixed, as a side effect of r478825.

Approved by:	portmgr (antoine)
PR:		230602
MFH:		2018Q4


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@481463 35697150-7ecd-e111-bb59-0022644237b5