games/alephone: Spell FFMPEG_* correctly
Disable FFMPEG option by default and mark it as broken since it does not build:

SDL_ffmpeg.c:89:103: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
struct SwsContext* getContext( SDL_ffmpegConversionContext **context, int inWidth, int inHeight, enum PixelFormat inFormat, int outWidth, int outHeight, enum PixelFormat outFormat )
                                                                                                      ^
SDL_ffmpeg.c:89:115: error: variable has incomplete type 'enum PixelFormat'
struct SwsContext* getContext( SDL_ffmpegConversionContext **context, int inWidth, int inHeight, enum PixelFormat inFormat, int outWidth, int outHeight, enum PixelFormat outFormat )
                                                                                                                  ^


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@514764 35697150-7ecd-e111-bb59-0022644237b5