www/faup: fix build with GCC-based architectures
Require new compiler because of:
/wrkdirs/usr/ports/www/faup/work/faup-1.5-48-g88dbbe2/src/lib/civetweb/civetweb.c:3614: error: #pragma GCC diagnostic not allowed inside functions
/wrkdirs/usr/ports/www/faup/work/faup-1.5-48-g88dbbe2/src/lib/civetweb/civetweb.c:3615: error: #pragma GCC diagnostic not allowed inside functions
/wrkdirs/usr/ports/www/faup/work/faup-1.5-48-g88dbbe2/src/lib/civetweb/civetweb.c:3621: error: #pragma GCC diagnostic not allowed inside functions

Approved by:	mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@500577 35697150-7ecd-e111-bb59-0022644237b5