www/py-django-app-plugins: convert to USES=python
- convert to USES=python
- limit python version to 2.x:
  """
  File "/usr/local/lib/python3.4/site-packages/app_plugins/models.py", line 24
    if not is_valid_label(name): raise RuntimeError, u"invalid label: " + name
                                                   ^
  SyntaxError: invalid syntax
  """

Approved by:	portmgr (blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@371155 35697150-7ecd-e111-bb59-0022644237b5