benchmarks/libcelero: Fix build
Fix breakage with clang10 by switching to clang-8:
error: loop variable 'udm' of type 'const std::__1::shared_ptr<celero::UserDefinedMeasurement>' creates a copy from type 'const std::__1::shared_ptr<celero::UserDefinedMeasurement>'
https://github.com/DigitalInBlue/Celero/issues/142

Reported by:	fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@529772 35697150-7ecd-e111-bb59-0022644237b5