Unbreak the build: as of recently, <assert.h> header file must be included before <Magick++.h> because of the following conflict:
  [...]: error: use of undeclared identifier '__assert'; did you mean
        'MagickCore::__assert'?
          assert( file.colorSpace() == Magick::sRGBColorspace );
          ^
  /usr/include/assert.h:56:36: note: expanded from macro 'assert'
  #define assert(e)       ((e) ? (void)0 : __assert(__func__, __FILE__, \

  /usr/include/assert.h:77:6: note: 'MagickCore::__assert' declared here
  void __assert(const char *, const char *, int, const char *) __dead2;

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@530885 35697150-7ecd-e111-bb59-0022644237b5