net-mgmt/resource-agents: Fix build with Clang
error: unknown warning option '-Wunsigned-char' [-Werror,-Wunknown-warning-option]

- Add missing DOCS option


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@477075 35697150-7ecd-e111-bb59-0022644237b5