devel/pecl-grpc: fix build on powerpc64 elfv2
Clang doesn't have sys/platform/ppc.h:
/wrkdirs/usr/ports/devel/pecl-grpc/work-php74/grpc-1.27.0/third_party/abseil-cpp/absl/base/internal/unscaledcycleclock.cc:24:10: fatal error: 'sys/platform/ppc.h' file not found
#include <sys/platform/ppc.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

__ppc_get_timebase() and __ppc_get_timebase_freq() are not supported on FreeBSD.

PR:		243995
Approved by:	vanilla (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@525666 35697150-7ecd-e111-bb59-0022644237b5