devel/gearmand-devel: fix build with GCC-based architectures
libtest/timer.hpp needs to include stdint.h for uint64.

./libtest/timer.hpp:55:36: error: 'int64_t' has not been declared
  void offset(int64_t minutes_arg, int64_t seconds_arg, int64_t nanoseconds);
                                   ^~~~~~~

PR:		237153
Approved by:	bdrewery (maintainer timeout), mat (mentor)
Differential Revision:	https://reviews.freebsd.org/D20114


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@500602 35697150-7ecd-e111-bb59-0022644237b5