graphics/py-mcomix: unbreak with non-default python
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_SITELIBDIR%%/mcomix/__pycache__/__init__.cpython-38.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/mcomix/__pycache__/about_dialog.cpython-38.pyc
Error: Orphaned: %%PYTHON_SITELIBDIR%%/mcomix/__pycache__/anime_tools.cpython-38.pyc
[...]
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%PYTHON_SITELIBDIR%%/mcomix/__pycache__/__init__.cpython-37.pyc
Error: Missing: %%PYTHON_SITELIBDIR%%/mcomix/__pycache__/about_dialog.cpython-37.pyc
Error: Missing: %%PYTHON_SITELIBDIR%%/mcomix/__pycache__/anime_tools.cpython-37.pyc
[...]

PR:		246084
Approved by:	Stefan Ehmann (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@533556 35697150-7ecd-e111-bb59-0022644237b5