devel/pygobject3-common: unbreak with DEFAULT_VERSIONS += python=3.9
pygobject-object.c:849:35: error: no member named 'tp_print' in '_typeobject'
                                  offsetof(PyTypeObject, tp_print) };
                                  ^                      ~~~~~~~~
/usr/include/stddef.h:75:31: note: expanded from macro 'offsetof'
 #define offsetof(type, field)   __offsetof(type, field)
                                 ^                ~~~~~
/usr/include/sys/cdefs.h:480:34: note: expanded from macro '__offsetof'
 #define __offsetof(type, field)  __builtin_offsetof(type, field)
                                  ^                        ~~~~~
pygobject-object.c:856:21: error: invalid application of 'sizeof' to an incomplete type 'int []'
    for (i = 0; i < G_N_ELEMENTS(slot_offsets); ++i)
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/glib-2.0/glib/gmacros.h:822:36: note: expanded from macro 'G_N_ELEMENTS'
 #define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                                 ^~~~~

Regressed by:	https://github.com/python/cpython/commit/f9bab74d5b34
Obtained from:	upstream


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@552487 35697150-7ecd-e111-bb59-0022644237b5