Fix plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/wallpapers/lumina-nature/LICENSE


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@457652 35697150-7ecd-e111-bb59-0022644237b5