deskutils/cairo-dock-plugins: fix plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/cairo-dock/libcd_kde-integration.so
Error: Orphaned: %%DATADIR%%/plug-ins/kde-integration/icon.png


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@557041 35697150-7ecd-e111-bb59-0022644237b5