Summary: comms/svxlink: Fix build with libc++ 3.8.0
During the exp-run in bug 208158, it was found that comms/svxlink gives errors
with libc++ 3.8.0 [1]:

/wrkdirs/usr/ports/comms/svxlink/work/svxlink-15.11/src/async/audio/AsyncAudioDe
+viceAlsa.cpp:551:7:
error: call to 'abs' is ambiguous
  if (::abs(real_rate - sample_rate) > 100)
      ^~~~~

This is because abs() is being called with an unsigned argument.  Fix this by
casting 'real_rate' to int, since it was assigned from 'sample_rate' anyhow.

PR:		ports/209371
Reported by:	@dim


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@416003 35697150-7ecd-e111-bb59-0022644237b5