lang/rust-nightly: unbreak after r489123
error[E0621]: explicit lifetime required in the type of `msg`
   --> src/tools/rls/src/server/mod.rs:185:21
    |
173 |       fn dispatch_message(&mut self, msg: &RawMessage) -> Result<(), jsonrpc::Error> {
    |                                           ----------- help: add explicit lifetime `'static` to the type of `msg`: `&'static server::message::RawMessage`
...
185 |                       <$n_action as LSPNotification>::METHOD => {
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime `'static` required
...
259 | /         match_action!(
260 | |             msg.method;
261 | |             notifications:
262 | |                 notifications::Initialized,
...   |
287 | |                 requests::CodeLensRequest;
288 | |         );
    | |__________- in this macro invocation


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@489131 35697150-7ecd-e111-bb59-0022644237b5