www/firefox: unbreak with Rust >= 1.21
error: doc comment not used by rustdoc
   --> servo/components/style/values/specified/image.rs:689:17
    |
689 |                 /// `to` keyword is mandatory in modern syntax.
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lint level defined here
   --> servo/components/style/lib.rs:26:9
    |
26  | #![deny(warnings)]
    |         ^^^^^^^^
    = note: #[deny(unused_doc_comment)] implied by #[deny(warnings)]

error: doc comment not used by rustdoc
   --> servo/components/style/values/specified/image.rs:695:17
    |
695 |                 /// There is no `to` keyword in webkit prefixed syntax. If it's consumed,
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: doc comment not used by rustdoc
    --> obj-x86_64-unknown-freebsd10.3/toolkit/library/x86_64-unknown-freebsd/release/build/style-65761c79245bf99f/out/gecko_properties.rs:9131:9
     |
9131 |         /// XXXManishearth this should also handle text zoom
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0106]: missing lifetime specifier
   --> obj-x86_64-unknown-freebsd10.3/toolkit/library/x86_64-unknown-freebsd/release/build/style-65761c79245bf99f/out/gecko/bindings.rs:569:9
    |
569 |      -> RawGeckoNodeBorrowedOrNull;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected lifetime parameter
    |
    = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
    = help: consider giving it an explicit bounded or 'static lifetime

error[E0106]: missing lifetime specifier
   --> obj-x86_64-unknown-freebsd10.3/toolkit/library/x86_64-unknown-freebsd/release/build/style-65761c79245bf99f/out/gecko/bindings.rs:841:9
    |
841 |      -> RawServoAnimationValueBorrowedOrNull;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected lifetime parameter
    |
    = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
    = help: consider giving it an explicit bounded or 'static lifetime

error: aborting due to 5 previous errors
error: Could not compile `style`.

Obtained from:	upstream (Firefox 57)
Ping:		@dumbbell @riggs- (unblocks lang/rust update)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@452499 35697150-7ecd-e111-bb59-0022644237b5