security/py-cryptography: Add enum43 to RUN_DEPENDS
Refactor *_DEPENDS to match setup.py's less than obvious dependencies

cffi is both a build/run dependency, the rest are only run dependencies.

This was causing a build failure for net-im/papyon:

  ImportError: No module named enum

Reported by:	kwm, pkg-fallout
Assisted by:	antoine


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@399860 35697150-7ecd-e111-bb59-0022644237b5