www/mohawk: unbreak on 12.0 after r312758
In file included from parse.c:17:
In file included from parse.y:34:
/usr/include/sys/capability.h:41:2: error: this file includes <sys/capability.h> which is deprecated [-Werror,-W#warnings]
 #warning this file includes <sys/capability.h> which is deprecated
  ^

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@433102 35697150-7ecd-e111-bb59-0022644237b5