Mark broken: Does not build
With gcc:
gnome-libtool: compile:  cc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I./../../gl -I./../includes -I./../includes -I./.. -I/usr/local/include -fPIC -O2 -pipe -fno-strict-aliasing -I/usr/local/include/p11-kit-1 -MT x509.lo -MD -MP -MF .deps/x509.Tpo -c x509.c  -fPIC -DPIC -o .libs/x509.o
x509.c: In function 'gnutls_x509_dn_get_rdn_ava':
x509.c:2018: error: dereferencing pointer to incomplete type
x509.c:2019: error: dereferencing pointer to incomplete type
x509.c:2033: error: dereferencing pointer to incomplete type
x509.c:2034: error: dereferencing pointer to incomplete type

With clang:
x509.c:2018:23: error: incomplete definition of type 'struct asn1_node_st'
  ava->oid.data = elem->value;
                  ~~~~^
/usr/local/include/libtasn1.h:117:18: note: forward declaration of 'struct asn1_node_st'
  typedef struct asn1_node_st asn1_node_st;
                 ^
x509.c:2019:23: error: incomplete definition of type 'struct asn1_node_st'
  ava->oid.size = elem->value_len;
                  ~~~~^
/usr/local/include/libtasn1.h:117:18: note: forward declaration of 'struct asn1_node_st'
  typedef struct asn1_node_st asn1_node_st;
                 ^
x509.c:2033:13: error: incomplete definition of type 'struct asn1_node_st'
  ptr = elem->value;
        ~~~~^
/usr/local/include/libtasn1.h:117:18: note: forward declaration of 'struct asn1_node_st'
  typedef struct asn1_node_st asn1_node_st;
                 ^
x509.c:2034:16: error: incomplete definition of type 'struct asn1_node_st'
  remlen = elem->value_len;
           ~~~~^
/usr/local/include/libtasn1.h:117:18: note: forward declaration of 'struct asn1_node_st'
  typedef struct asn1_node_st asn1_node_st;
                 ^

Reported by:	pkg-fallout since november 2013


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@345572 35697150-7ecd-e111-bb59-0022644237b5