Fix the build on 9.x.
Add a missing include so that the port builds on 9.3-{amd64,i386}:

  /wrkdirs/usr/ports/graphics/hugin/work/hugin-2015.0.0/src/hugin_cpfind/localfeatures/RansacFiltering.cpp: In function 'int genint(int)':
  /wrkdirs/usr/ports/graphics/hugin/work/hugin-2015.0.0/src/hugin_cpfind/localfeatures/RansacFiltering.cpp:28:31: error: 'rand' was not declared in this scope
       return (int)((double)rand()*x/(double)RAND_MAX);
                               ^
  /wrkdirs/usr/ports/graphics/hugin/work/hugin-2015.0.0/src/hugin_cpfind/localfeatures/RansacFiltering.cpp:28:43: error: 'RAND_MAX' was not declared in this scope
       return (int)((double)rand()*x/(double)RAND_MAX);
                                           ^

The quarterly branch is not affected, it still contains hugin 2013.0.0.

Approved by:	portmgr blanket approval (trivial and tested build fix)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@402987 35697150-7ecd-e111-bb59-0022644237b5