dns/packetq: require C++11 toolchain (on powerpc*, mips*, sparc*)
cc1plus: error: unrecognized command line option "-std=c++0x"

In file included from dns.cpp:22:
In file included from ./dns.h:31:
In file included from ./packet_handler.h:33:
In file included from ./sql.h:43:
./variant.h:297:34: error: expected '(' for function-style cast or type construction
            return std::hash<bool>()(m_val.m_bool);
                             ~~~~^
./variant.h:297:20: error: no member named 'hash' in namespace 'std'; did you mean simply 'hash'?
            return std::hash<bool>()(m_val.m_bool);
                   ^~~~~~~~~
                   hash
./variant.h:293:17: note: 'hash' declared here
    std::size_t hash() const
                ^
./variant.h:297:36: error: expected expression
            return std::hash<bool>()(m_val.m_bool);
                                   ^
./variant.h:299:33: error: expected '(' for function-style cast or type construction
            return std::hash<int>()(m_val.m_int);
                             ~~~^
./variant.h:299:20: error: no member named 'hash' in namespace 'std'; did you mean simply 'hash'?
            return std::hash<int>()(m_val.m_int);
                   ^~~~~~~~~
                   hash
./variant.h:293:17: note: 'hash' declared here
    std::size_t hash() const
                ^
./variant.h:299:35: error: expected expression
            return std::hash<int>()(m_val.m_int);
                                  ^
./variant.h:301:35: error: expected '(' for function-style cast or type construction
            return std::hash<float>()(m_val.m_float);
                             ~~~~~^
./variant.h:301:20: error: no member named 'hash' in namespace 'std'; did you mean simply 'hash'?
            return std::hash<float>()(m_val.m_float);
                   ^~~~~~~~~
                   hash
./variant.h:293:17: note: 'hash' declared here
    std::size_t hash() const
                ^
./variant.h:301:37: error: expected expression
            return std::hash<float>()(m_val.m_float);
                                    ^
In file included from dns.cpp:22:
In file included from ./dns.h:31:
In file included from ./packet_handler.h:33:
./sql.h:1766:8: error: explicit specialization of non-template struct 'hash'
struct hash<std::vector<packetq::Variant> > {
       ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 errors generated.

Reported by:	pkg-fallout (mips64)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@456077 35697150-7ecd-e111-bb59-0022644237b5