Fix build with clang 6 (C++11 requires a space between literal and identifier)
Mark FOX17 option broken (Not related to clang 6 in particular, the FOX-1.7
API is ever changing due to being a development version. This project
appears to be dead, so I'm not sure it is worth fixing.)
recorder.cpp:104:9: error: no matching member function for call to 'prepend'
        NewMessage();
        ^~~~~~~~~~~~
recorder.cpp:51:6: note: expanded from macro 'NewMessage'
list.prepend((FXObject*)mm);
~~~~~^~~~~~~
/usr/local/include/fox-1.7/FXObjectList.h:256:10: note: candidate function not viable: no known conversion from 'FX::FXObject *' to 'MacroMessage *' for 1st argument
  FXbool prepend(TYPE* object){ return FXObjectList::prepend(object); }
         ^
/usr/local/include/fox-1.7/FXObjectList.h:265:10: note: candidate function not viable: no known conversion from 'FX::FXObject *' to 'const FXObjectListOf<MacroMessage>' for 1st argument
  FXbool prepend(const FXObjectListOf<TYPE>& objects){ return FXObjectList::prepend(objects); }
         ^
/usr/local/include/fox-1.7/FXObjectList.h:259:10: note: candidate function not viable: requires 2 arguments, but 1 was provided
  FXbool prepend(TYPE* object,FXival n){ return FXObjectList::prepend(object,n); }
         ^
/usr/local/include/fox-1.7/FXObjectList.h:262:10: note: candidate function not viable: requires 2 arguments, but 1 was provided
  FXbool prepend(TYPE** objects,FXival n){ return FXObjectList::prepend(objects,n); }
         ^

Rename/remake patches


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@461984 35697150-7ecd-e111-bb59-0022644237b5