- %D is based on @cwd, not PREFIX; Fix false-postives when using pkg_install   and @cwd has changed away from PREFIX:
    plist:
      @cwd /
      @dirrmtry var/spool/dma

    ====> Checking for pkg-plist issues (check-plist)
    ===> Parsing plist
    DIR '/usr/local/etc/dma' CWD: /usr/local
    DIR '/usr/local/var/spool/dma' CWD:
    DIR 'share/licenses/dma-v0.9,1' CWD: /usr/local
    DIR '/usr/local/share/licenses' CWD: /usr/local
    ===> Checking for items in STAGEDIR missing from pkg-plist
    Error: Orphaned: @unexec rmdir "/var/spool/dma" >/dev/null 2>&1 || :
    ===> Checking for directories owned by MTREEs
    ===> Checking for directories handled by dependencies
    ===> Checking for items in pkg-plist which are not in STAGEDIR
    Error: Missing: @dirrmtry var/spool/dma
    ===> Error: Plist issues found.

With hat:	portmgr
Reported by:	erwin


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@354382 35697150-7ecd-e111-bb59-0022644237b5