- add missing man pages to pkg-plist (fix package building)
from poudriere log:
 ===> Parsing plist
 ===> Checking for items in STAGEDIR missing from pkg-plist
 Error: Orphaned: man/man3/d2i_AutoPrivateKey.3.gz
 Error: Orphaned: man/man3/d2i_PrivateKey.3.gz
 Error: Orphaned: man/man3/d2i_Private_key.3.gz
 Error: Orphaned: man/man3/i2d_PrivateKey.3.gz
 ===> Error: Plist issues found.
 *** Error code 1
 ====>> Error: check-plist failures detected
 !!! build failure encountered !!!

Approved by:	blanket


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@422739 35697150-7ecd-e111-bb59-0022644237b5