databases/skytools: Unbreak build with PostgreSQL 11
logutriga.c:57:24: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
if (tupdesc->attrs[i]->attisdropped)
~~~~~~~~~~~~~~~~~^~
.
logutriga.c:148:24: error: member reference type 'FormData_pg_attribute' (aka 'struct FormData_pg_attribute') is not a pointer; did you mean to use '.'?
if (tupdesc->attrs[i]->attisdropped)
~~~~~~~~~~~~~~~~~^~
.
2 errors generated.

http://package18.nyi.freebsd.org/data/120amd64-default-PR239514/2019-07-29_20h41m52s/logs/skytools-3.2_3.log

While here deprecate it.  It was last updated in 2014 and seems to
have been abandoned.

PR:		239652
Approved by:	sam@cassiba.com (maintainer timeout, 2 weeks)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@509208 35697150-7ecd-e111-bb59-0022644237b5