- Fix documentation build - Add textproc/py-sphinx_rtd_theme and textproc/towncrier to build dependencies - Add files/patch-docs_conf.py to fix ModuleNotFoundError (virtualenv) - Set LANG and LC_ALL environment variables to mitigate a RuntimeError during the   build stage of the doc.:
  RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@512421 35697150-7ecd-e111-bb59-0022644237b5