graphics/lightzone: Fix build with GCC 9
- Apply upstream commit 376ec67ddfb1 to update bundled dcraw to 9.28

[...]
[exec] -----> Entering dcraw
[exec] gcc9 -c -g -march=pentium4 -mtune=generic -march=pentium4 -msse2 -mfpmath=sse -fPIC -O3 -fno-trapping-math -fomit-frame-pointer -fopenmp -Wno-unused-result  -DNODEPS -DLIGHTZONE -Dfgetc=getc_unlocked   dcraw_lz.c
[exec] dcraw_lz.c: In function 'vng_interpolate':
[exec] dcraw_lz.c:4543:10: warning: assignment to 'short unsigned int (*)[4]' from incompatible pointer type 'short unsigned int *' [-Wincompatible-pointer-types]
[exec]  4543 |   rowtmp = (ushort*)malloc(4 * width * 4 * sizeof(ushort));
[exec]       |          ^
[exec] dcraw_lz.c: In function 'wavelet_denoise':
[exec] dcraw_lz.c:4170:32: error: 'noise' not specified in enclosing 'parallel'
[exec]  4170 |       thold = threshold * noise[lev];
[exec]       |                           ~~~~~^~~~~
[exec] dcraw_lz.c:4149:13: error: enclosing 'parallel'
[exec]  4149 |     #pragma omp parallel for    \
[exec]       |             ^~~
[exec] dcraw_lz.c: In function 'xtrans_interpolate':
[exec] dcraw_lz.c:4846:19: error: 'orth' not specified in enclosing 'parallel'
[exec]  4846 |  if (fcol(row+orth[d],col+orth[d+2]) == 1) ng=0; else ng++;
[exec]       |               ~~~~^~~
[exec] dcraw_lz.c:4757:31: note: in definition of macro 'fcol'
[exec]  4757 | #define fcol(row,col) xtrans[(row+6) % 6][(col+6) % 6]
[exec]       |                               ^~~
[exec] dcraw_lz.c:4827:9: error: enclosing 'parallel'
[exec]  4827 | #pragma omp parallel default (none)   \
[exec]       |         ^~~
[exec] dcraw_lz.c:4849:25: error: 'patt' not specified in enclosing 'parallel'
[exec]  4849 |    v = orth[d  ]*patt[g][c*2] + orth[d+1]*patt[g][c*2+1];
[exec]       |                  ~~~~~~~^~~~~
[exec] dcraw_lz.c:4827:9: error: enclosing 'parallel'
[exec]  4827 | #pragma omp parallel default (none)   \
[exec]       |         ^~~
[exec] dcraw_lz.c:5021:7: error: 'dir' not specified in enclosing 'parallel'
[exec]  5021 |  f=dir[d & 3];
[exec]       |    ~~~^~~~~~~
[exec] dcraw_lz.c:4827:9: error: enclosing 'parallel'
[exec]  4827 | #pragma omp parallel default (none)   \
[exec]       |         ^~~

http://package18.nyi.freebsd.org/data/120amd64-default-PR238330/2019-06-09_20h26m27s/logs/errors/lightzone-4.1.8.3_3.log

PR:		238664
Reported by:	antoine (via exp-run in PR 238330)
Submitted by:	jbeich
Approved by:	yuri (maintainer timeout, 2 weeks)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@505744 35697150-7ecd-e111-bb59-0022644237b5