- Mark MAKE_JOBS_UNSAFE
guild-boot.c is used before it's generated:

guile.c:1791:10: fatal error: 'guile-boot.c' file not found
...
../build-aux/guile-baux/gbaux-do as-C-byte-array -v high -t char guile-boot.puny > guile-boot.c


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@399126 35697150-7ecd-e111-bb59-0022644237b5