x11/cde: Add dtlogin rc script
Remove double ksh dependency

Pet portlint

Mark BROKEN on head:

cc -o dthelpview -O2 -fno-strict-aliasing -Wno-write-strings -Wno-unused-result -Wno-deprecated-register -pipe    -L../../../exports/lib -L/usr/local/lib -L/usr/local/lib Main.o ManPage.o Util.o version.o -lDtHelp -lDtSvc -ltt -lXm -lXt -lSM -lICE -lXext -lX11 -L/usr/local/dt/lib -L/usr/local/lib -L/usr/local/lib   -liconv  -lm -lstdc++
ld: error: ../../../exports/lib/libDtHelp.so: undefined reference to jpeg_CreateDecompress

[...]


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@504733 35697150-7ecd-e111-bb59-0022644237b5