graphics/py-pillow: Fix OPT_VARS, Enable WEBP by default
After converting if PORT_OPTIONS:MOPTION PYDISTUTILS_BUILDARGS to
OPTION_VARS=PYDISTUTILS_BUILDARGS in r409464 [1], it was reported
that the port failed to build with the following error:

  ValueError: --enable-tcl requested but tcl not found

Investigation revealed that only the first of the TKINTER_VARS{_OFF}
values was being assigned. The root cause appears to be that
OPTIONS_VARS=VAR=<value> does not support multiple space-separated
values, unless:

a) Values are quoted: OPTION_VARS=VAR="value1 value1", OR
b) Multiple assignments are made: OPTION_VAR=VAR+=value1 VAR+=value2

This change wraps the assign for TKINTER_VARS{_OFF} in quotes.

It's probably worth improving the OPTION_VARS mechanism to support (a)
in Mk/bsd.options.mk instead in the long term.

While I'm here:

- Use the 'saveopts' command to save all PYDISTUTILS_BUILDARGS in
  setup.cfg so they are used in the install stage, fixing certain errors
- Enable WEBP option by default (Hi pkg users!)

[1] https://svnweb.freebsd.org/changeset/ports/409464

PR:		207470
Reported by:	olgeni
Reported by:	Vladimir Omelchuk <admin vladiom com ua>
Reported by:	Oliver Hartmann <ohartman zedat fu-berlin de>


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@409505 35697150-7ecd-e111-bb59-0022644237b5