Mark broken: Does not compile
on 8 and 9:
 cc -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"alliance\" -DVERSION=\"5.0\" -DYYTEXT_POINTER=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DHAVE_FCNTL_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STRINGS_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBM=1 -DHAVE_LIBM=1 -DHAVE_LIBM=1 -DHAVE_LIBM=1 -DHAVE_UNISTD_H=1 -DHAVE_FORK=1 -DHAVE_VFORK=1 -DHAVE_WORKING_VFORK=1 -DHAVE_WORKING_FORK=1 -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DRETSIGTYPE=void -DHAVE_MOTIF=1 -DHAVE_XPM=1 -DHAVE_XPM=1 -DHAVE_X11_XPM_H=1 -DHAVE_XP=1 -DHAVE_MOTIF=1 -DHAVE_XMUSEVERSION=1 -DHAVE_XMINSTALLIMAGE=1 "-DALLIANCE_VERSION=\"5.0 20090901\"" -DALLIANCE_TOP=\"/usr/local/alliance\" -I. -I. -I../../mbk/src -I../../pat/src -O2 -pipe -fno-strict-aliasing -MT pat_decl_y.lo -MD -MP -MF .deps/pat_decl_y.Tpo -c pat_decl_y.c  -fPIC -DPIC -o .libs/pat_decl_y.o
y.tab.c:562: error: duplicate 'extern'

on 10 and head:
elp.c:252:1: error: non-void function 'elpLotrsShrink' should return a value [-Wreturn-type]
return ;
^
elp.c:460:1: error: non-void function 'elpLofigCapaDiff' should return a value [-Wreturn-type]
return ;
^
elp.c:490:1: error: non-void function 'elpLofigCapaGrid' should return a value [-Wreturn-type]
return ;
^
elp.c:518:1: error: non-void function 'elpLofigShrink' should return a value [-Wreturn-type]
return ;

Reported by:	pkg-fallout since august 2013


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@344015 35697150-7ecd-e111-bb59-0022644237b5